from parsing import *

CLIENT_SIDE = 0
SERVER_SIDE = 1

#TYPE_WINDOW_CLICK = 11

client_packet_spec = {
    0x00: [],   # Keep-alive packet
    0x01: [('proto_version',parse_int),
           ('username',parse_string),
           ('password',parse_string),
           ('map_seed',parse_long),
           ('dimension',parse_byte)],
    0x02: [('username',parse_string)],
    0x03: [('chat_msg',parse_string)],
    0x05: [('eid',parse_int),
           ('slot',parse_short),
           ('item_id',parse_short),
           ('unknown',parse_short)],
    0x07: [('eid',parse_int),
           ('target_eid',parse_int),
           ('left_click',parse_bool)],
    0x09: [], # Respawnn packet
    0x0a: [('on_ground',parse_bool)],
    0x0b: [('x',parse_double),
           ('y',parse_double),
           ('stance',parse_double),
           ('z',parse_double),
           ('on_ground',parse_bool)],
    0x0c: [('yaw',parse_float),
           ('pitch',parse_float),
           ('on_ground',parse_bool)],
    0x0d: [('x',parse_double),
           ('y',parse_double),
           ('stance',parse_double),
           ('z',parse_double),
           ('yaw',parse_float),
           ('pitch',parse_float),
           ('on_ground',parse_bool)],
    0x0e: [('status',parse_byte),
           ('x',parse_int),
           ('y',parse_byte),
           ('z',parse_int),
           ('face',parse_byte)],
    0x0f: [('x',parse_int),
           ('y',parse_byte),
           ('z',parse_int),
           ('dir',parse_byte),
           ('id',parse_short),
           ('details',parse_item_details)],
    0x10: [('slot_id', parse_short)],
    0x12: [('eid',parse_int),
           ('animation',parse_byte)],
    0x13: [('eid',parse_int),
           ('action', parse_byte)],
    0x15: [('eid',parse_int),
           ('item',parse_short),
           ('count',parse_byte),
           ('data',parse_short),
           ('x',parse_int),
           ('y',parse_int),
           ('z',parse_int),
           ('rotation',parse_byte),
           ('pitch',parse_byte),
           ('roll',parse_byte)],
    0x1b: [('d1', parse_float),
           ('d2', parse_float),
           ('d3', parse_float),
           ('d4', parse_float),
           ('d5', parse_bool),
           ('d6', parse_bool)],
    0x1c: [('eid',parse_int),
           ('vel_x',parse_short),
           ('vel_y',parse_short),
           ('vel_z',parse_short)],
    0x27: [('eid',parse_int),
           ('vehicle_id',parse_int)],
    0x28: [('eid',parse_int),
           ('metadata',parse_metadata)],
    0x34: [('chunk_x',parse_int),
           ('chunk_z',parse_int),
           ('array_lengths',parse_short),
           ('arrays',parse_multi_block_change)],
    0x35: [('x',parse_int),
           ('y',parse_byte),
           ('z',parse_int),
           ('block_type',parse_byte),
           ('block_metadata',parse_byte)],
    0x65: [('window_id', parse_byte)],
    0x66: [('window_id', parse_byte),
           ('slot', parse_short),
           ('is_right_click', parse_bool),
           ('action_num', parse_short),
           ('item_id', parse_short),
           ('item_details', parse_item_details)],
    0x6a: [('window_id', parse_byte),
           ('action_num', parse_short),
           ('accepted', parse_bool)],
    0x82: [('x', parse_int),
           ('y', parse_short),
           ('z', parse_int),
           ('text1', parse_string),
           ('text2', parse_string),
           ('text3', parse_string),
           ('text4', parse_string)],
    0xff: [('reason', parse_string)]}

server_packet_spec = {
    0x00: [],
    0x01: [('eid',parse_int),
           ('reserved',parse_string),
           ('reserved',parse_string),
           ('map_seed',parse_long),
           ('dimension',parse_byte)],
    0x02: [('hash',parse_string)],
    0x03: [('chat_msg',parse_string)],
    0x04: [('time',parse_long)],
    0x05: [('eid', parse_int),
           ('slot_id', parse_short),
           ('item_id', parse_short),
           ('unknown', parse_short)],
    0x06: [('x',parse_int),
           ('y',parse_int),
           ('z',parse_int)],
    0x08: [('health',parse_short)],
    0x0b: [('x',parse_double),
           ('y',parse_double),
           ('stance',parse_double),
           ('z',parse_double),
           ('on_ground',parse_bool)],
    0x0d: [('x',parse_double),
           ('stance',parse_double),
           ('y',parse_double),
           ('z',parse_double),
           ('yaw',parse_float),
           ('pitch',parse_float),
           ('on_ground',parse_bool)],
    0x0e: [('status',parse_byte),
           ('x',parse_int),
           ('y',parse_byte),
           ('z',parse_int),
           ('face',parse_byte)],
    0x0f: [('x',parse_int),
           ('y',parse_byte),
           ('z',parse_int),
           ('dir',parse_byte),
           ('id',parse_short),
           ('details',parse_item_details)],
    0x10: [('slot_id', parse_short)],
    0x11: [('eid', parse_int),
           ('unknown', parse_byte),
           ('x', parse_int),
           ('y', parse_byte),
           ('z', parse_int)],
    0x12: [('eid',parse_int),
           ('animation',parse_byte)],
    0x13: [('eid',parse_int),
           ('action', parse_byte)],
    0x14: [('eid', parse_int),
           ('name', parse_string),
           ('x', parse_int),
           ('y', parse_int),
           ('z', parse_int),
           ('rotation', parse_byte),
           ('pitch', parse_byte),
           ('curr_item', parse_short)],
    0x15: [('eid',parse_int),
           ('item',parse_short),
           ('count',parse_byte),
           ('data',parse_short),
           ('x',parse_int),
           ('y',parse_int),
           ('z',parse_int),
           ('rotation',parse_byte),
           ('pitch',parse_byte),
           ('roll',parse_byte)],
    0x16: [('item_eid',parse_int),
           ('collector_eid',parse_int)],
    0x17: [('eid',parse_int),
           ('type',parse_byte),
           ('x',parse_int),
           ('y',parse_int),
           ('z',parse_int)],
    0x18: [('eid',parse_int),
           ('mob_type',parse_byte),
           ('x',parse_int),
           ('y',parse_int),
           ('z',parse_int),
           ('yaw',parse_byte),
           ('pitch',parse_byte),
           ('metadata',parse_metadata)],
    0x19: [('eid', parse_int),
           ('title', parse_string),
           ('x', parse_int),
           ('y', parse_int),
           ('z', parse_int),
           ('type', parse_int)],
    0x1b: [('d1', parse_float),
           ('d2', parse_float),
           ('d3', parse_float),
           ('d4', parse_float),
           ('d5', parse_bool),
           ('d6', parse_bool)],
    0x1c: [('eid',parse_int),
           ('vel_x',parse_short),
           ('vel_y',parse_short),
           ('vel_z',parse_short)],
    0x1d: [('eid',parse_int)],
    0x1e: [('eid', parse_int)],
    0x1f: [('eid',parse_int),
           ('dx',parse_byte),
           ('dy',parse_byte),
           ('dz',parse_byte)],
    0x20: [('eid', parse_int),
           ('yaw', parse_byte),
           ('pitch', parse_byte)],
    0x21: [('eid',parse_int),
           ('dx',parse_byte),
           ('dy',parse_byte),
           ('dz',parse_byte),
           ('yaw',parse_byte),
           ('pitch',parse_byte)],
    0x22: [('eid', parse_int),
           ('x', parse_int),
           ('y', parse_int),
           ('z', parse_int),
           ('yaw', parse_byte),
           ('pitch', parse_byte)],
    0x26: [('eid',parse_int),
           ('status',parse_byte)],
    0x27: [('eid', parse_int),
           ('vehicle_id', parse_int)],
    0x28: [('eid',parse_int),
           ('metadata',parse_metadata)],
    0x32: [('x',parse_int),
           ('z',parse_int),
           ('mode',parse_bool)],
    0x33: [('x',parse_int),
           ('y',parse_short),
           ('z',parse_int),
           ('size_x',parse_byte),
           ('size_y',parse_byte),
           ('size_z',parse_byte),
           ('data_size',parse_int),
           ('data',parse_chunk)],
    0x34: [('chunk_x',parse_int),
           ('chunk_z',parse_int),
           ('array_lengths',parse_short),
           ('arrays',parse_multi_block_change)],
    0x35: [('x',parse_int),
           ('y',parse_byte),
           ('z',parse_int),
           ('block_type',parse_byte),
           ('block_metadata',parse_byte)],
    0x36: [('x', parse_int),
           ('y', parse_short),
           ('z', parse_int),
           ('instrument_type', parse_byte),
           ('pitch', parse_byte)],
    0x3c: [('x', parse_double),
           ('y', parse_double),
           ('z', parse_double),
           ('unknown', parse_float),
           ('count', parse_int),
           ('records', parse_explosion_record)],
    0x64: [('window_id', parse_byte),
           ('inv_type', parse_byte),
           ('window_title', parse_string),
           ('num_slots', parse_byte)],
    0x65: [('window_id', parse_byte)],
    0x67: [('window_id',parse_byte),
           ('slot',parse_short),
           ('item_id',parse_short),
           ('count_uses',parse_set_slot)],
    0x68: [('window_id',parse_byte),
           ('count',parse_short),
           ('inventory',parse_inventory)],
    0x69: [('window_id', parse_byte),
           ('progress_bar',parse_short),
           ('value',parse_short)],
    0x6a: [('window_id', parse_byte),
           ('action_num', parse_short),
           ('accepted', parse_bool)],
    0x82: [('x', parse_int),
           ('y', parse_short),
           ('z', parse_int),
           ('text1', parse_string),
           ('text2', parse_string),
           ('text3', parse_string),
           ('text4', parse_string)],
    0xff: [('reason', parse_string)]}

packet_spec = [ client_packet_spec, server_packet_spec ]


